# Generated by Django 3.1.5 on 2021-02-11 10:03

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=250, unique=True)),
                ('user_id', models.CharField(max_length=250)),
                ('category_id', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=25555, null=True)),
                ('product_home_image', models.FileField(blank=True, null=True, upload_to=product.models.Product.folder_path)),
                ('product_specification', models.TextField(blank=True, max_length=65500, null=True)),
                ('certificate_by', models.CharField(blank=True, max_length=250, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=product.models.Product.folder_path)),
                ('price', models.FloatField(max_length=250)),
                ('selling_price', models.FloatField(max_length=250)),
                ('price_off', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Publish Review', 'Publish Review'), ('Draft', 'Draft')], max_length=250)),
                ('likes', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('heart', models.IntegerField(default=0)),
                ('total_comment', models.IntegerField(default=0)),
                ('total_review', models.FloatField(default=0)),
                ('is_feature', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=10000, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('available_stock', models.IntegerField(default=0)),
                ('delivery_charge', models.IntegerField(default=0)),
                ('is_cod', models.BooleanField(default=True)),
                ('delivery_time', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCanvas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('canvas', models.CharField(max_length=250)),
                ('canvas_image', models.FileField(blank=True, null=True, upload_to=product.models.ProductCanvas.folder_path)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('comment', models.TextField(max_length=65500)),
                ('sub_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('product_gallery_image', models.FileField(blank=True, null=True, upload_to=product.models.ProductGalleryImage.folder_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductHeart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('review', models.IntegerField(default=1)),
                ('review_description', models.TextField(blank=True, max_length=65500, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=250)),
                ('size_image', models.FileField(blank=True, null=True, upload_to=product.models.ProductSize.folder_path)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
