# Generated by Django 3.0.5 on 2020-12-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='account_id',
            field=models.IntegerField(default=58848529, unique=True),
        ),
    ]
