# Generated by Django 3.0.5 on 2020-12-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyUser', '0002_auto_20201209_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='account_id',
            field=models.IntegerField(default=23892286, unique=True),
        ),
    ]
