# Generated by Django 3.1.3 on 2020-11-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0002_auto_20201117_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
    ]
