# Generated by Django 3.1.3 on 2020-11-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0003_user_is_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
