# Generated by Django 3.0.5 on 2020-12-09 06:38

import DMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyUser', '0002_auto_20201209_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='DMS.AllFolders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CompanyUser.CompanyUser')),
            ],
        ),
        migrations.CreateModel(
            name='ScanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('assigned_type', models.CharField(choices=[('1', 'User'), ('2', 'department')], default='1', max_length=10)),
                ('selected_user', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=DMS.models.ScanFile.folder_path)),
                ('file_size', models.CharField(default='0', max_length=255)),
                ('file_version', models.CharField(default='0', max_length=255)),
                ('file_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('file_content', models.TextField(blank=True, max_length=5000, null=True)),
                ('upload_type', models.CharField(max_length=100)),
                ('batch_no', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('folder_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMS.AllFolders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CompanyUser.CompanyUser')),
                ('user_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_user_department', to='CompanyUser.UserDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_tag', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS.ScanFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyUser.CompanyUser')),
            ],
        ),
    ]
